# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'RealmRubyMotionSimpleExample'
  app.external_frameworks << '../../../../build/ios-static/Realm.framework'
  app.vendor_project 'models', :static, :cflags => '-F ../../../../../build/ios-static/'
end
