# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'RealmRubyMotionSimpleExample'
  app.vendor_project '../../../../build/ios/Realm.framework', :static, :products => ['Realm']
  app.vendor_project 'models', :static, :cflags => '-F ../../../../../build/ios/'
end
