lib_LIBRARIES = libtightdb-objc.a

ADD_CFLAGS_INCLUDE = -I../../Deliv

libtightdb_objc_a_SOURCES       = Table.mm Cursor.mm Group.mm Query.mm
libtightdb_objc_a_LDFLAGS       = -ltightdb
libtightdb_objc_a_LDFLAGS_DEBUG = -ltightdb-dbg

include ../../generic.mk
