
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version:
 - 12.2
 - 12.4
 - 12.5.1
 - 13.0
target:
 - docs
 - swiftlint
 - osx
 - osx-encryption
 - osx-object-server
 - swiftpm
 - swiftpm-debug
 - swiftpm-address
 - swiftpm-thread
 - swiftpm-ios
 - ios-static
 - ios-dynamic
 - watchos
 - tvos
 - osx-swift
 - ios-swift
 - tvos-swift
 - osx-swift-evolution
 - ios-swift-evolution
 - tvos-swift-evolution
 - catalyst
 - catalyst-swift
 - xcframework
 - cocoapods-osx
 - cocoapods-ios
 - cocoapods-ios-dynamic
 - cocoapods-watchos
 - swiftui-ios
 - swiftui-server-ios
configuration:
 - N/A

exclude:

  - xcode_version: 12.2
    target: docs

  - xcode_version: 12.4
    target: docs

  - xcode_version: 12.5.1
    target: docs

  - xcode_version: 12.2
    target: swiftlint

  - xcode_version: 12.4
    target: swiftlint

  - xcode_version: 12.5.1
    target: swiftlint

  - xcode_version: 12.4
    target: osx-encryption

  - xcode_version: 12.5.1
    target: osx-encryption

  - xcode_version: 12.4
    target: osx-object-server

  - xcode_version: 12.5.1
    target: osx-object-server

  - xcode_version: 12.2
    target: swiftpm-address

  - xcode_version: 12.4
    target: swiftpm-address

  - xcode_version: 12.5.1
    target: swiftpm-address

  - xcode_version: 12.2
    target: swiftpm-thread

  - xcode_version: 12.4
    target: swiftpm-thread

  - xcode_version: 12.5.1
    target: swiftpm-thread

  - xcode_version: 12.2
    target: swiftpm-ios

  - xcode_version: 12.4
    target: swiftpm-ios

  - xcode_version: 12.5.1
    target: swiftpm-ios

  - xcode_version: 12.4
    target: ios-static

  - xcode_version: 12.5.1
    target: ios-static

  - xcode_version: 12.4
    target: ios-dynamic

  - xcode_version: 12.5.1
    target: ios-dynamic

  - xcode_version: 12.4
    target: watchos

  - xcode_version: 12.5.1
    target: watchos

  - xcode_version: 12.4
    target: tvos

  - xcode_version: 12.5.1
    target: tvos

  - xcode_version: 12.4
    target: ios-swift

  - xcode_version: 12.5.1
    target: ios-swift

  - xcode_version: 12.4
    target: tvos-swift

  - xcode_version: 12.5.1
    target: tvos-swift

  - xcode_version: 12.2
    target: osx-swift-evolution

  - xcode_version: 12.4
    target: osx-swift-evolution

  - xcode_version: 12.5.1
    target: osx-swift-evolution

  - xcode_version: 12.2
    target: ios-swift-evolution

  - xcode_version: 12.4
    target: ios-swift-evolution

  - xcode_version: 12.5.1
    target: ios-swift-evolution

  - xcode_version: 12.2
    target: tvos-swift-evolution

  - xcode_version: 12.4
    target: tvos-swift-evolution

  - xcode_version: 12.5.1
    target: tvos-swift-evolution

  - xcode_version: 12.4
    target: catalyst

  - xcode_version: 12.5.1
    target: catalyst

  - xcode_version: 12.4
    target: catalyst-swift

  - xcode_version: 12.5.1
    target: catalyst-swift

  - xcode_version: 12.2
    target: xcframework

  - xcode_version: 12.4
    target: xcframework

  - xcode_version: 12.5.1
    target: xcframework

  - xcode_version: 12.4
    target: cocoapods-ios

  - xcode_version: 12.5.1
    target: cocoapods-ios

  - xcode_version: 12.4
    target: cocoapods-ios-dynamic

  - xcode_version: 12.5.1
    target: cocoapods-ios-dynamic

  - xcode_version: 12.4
    target: cocoapods-watchos

  - xcode_version: 12.5.1
    target: cocoapods-watchos

  - xcode_version: 12.2
    target: swiftui-ios

  - xcode_version: 12.4
    target: swiftui-ios

  - xcode_version: 12.5.1
    target: swiftui-ios

  - xcode_version: 12.2
    target: swiftui-server-ios

  - xcode_version: 12.4
    target: swiftui-server-ios

  - xcode_version: 12.5.1
    target: swiftui-server-ios
