# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin

xcode_version:
  - 9.2
  - 9.3
  - 9.4
  - 10.0
  - 10.1
  - 10.2.1
target:
  - osx
  - docs
  - ios-static
  - ios-dynamic
  - ios-swift
  - osx-swift
  - watchos
  - cocoapods-ios
  - cocoapods-osx
  - cocoapods-watchos
  - swiftlint
  - tvos
  - osx-encryption
  - osx-object-server

  # These are disabled because the machinen with the devices attached is currently offline
  # - ios-device-objc-ios8
  # - ios-device-objc-ios10
  # - tvos-device
  # These are disabled because they were very unreliable on CI
  # - ios-device-swift-ios8
  # - ios-device-swift-ios10
configuration:
  - Debug
  - Release

# Combinations have to be excluded in a way that's hard to read.
# This table shows which jobs will run:

# +------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
# | Configuration Matrix | osx | docs | ios-static | ios-dynamic | ios-swift | osx-swift | watchos | cocoapods-ios | cocoapods-osx | cocoapods-watchos | swiftlint | tvos | osx-encryption | osx-object-server | ios-device-objc-ios8 | ios-device-swift-ios8 | ios-device-objc-ios10 | ios-device-swift-ios10 | tvos-device |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | ------------- | ------------- | ----------------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 9.2   | Debug        | X   |      | X          |             |           |           |         |               |               |                   |           |      |                |                   |                      |                       |                       |                        |             |
# | 9.2   | Release      | X   |      | X          | X           | X         | X         | X       | X             | X             | X                 |           | X    | X              | X                 | X                    |                       | X                     |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | ------------- | ------------- | ----------------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 9.3   | Debug        | X   |      |            |             |           |           |         |               |               |                   |           |      |                |                   |                      |                       |                       |                        |             |
# | 9.3   | Release      | X   |      | X          | X           | X         | X         | X       | X             | X             | X                 |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | ------------- | ------------- | ----------------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 9.4   | Debug        | X   |      |            |             |           |           |         |               |               |                   |           |      |                |                   |                      |                       |                       |                        |             |
# | 9.4   | Release      | X   |      | X          | X           | X         | X         | X       | X             | X             | X                 |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | ------------- | ------------- | ----------------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 10.0  | Debug        | X   |      |            |             |           |           |         |               |               |                   |           |      |                |                   |                      |                       |                       |                        |             |
# | 10.0  | Release      | X   |      | X          | X           | X         | X         | X       | X             | X             | X                 |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | ------------- | ------------- | ----------------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 10.1  | Debug        | X   |      |            |             |           |           |         |               |               |                   |           |      |                |                   |                      |                       |                       |                        |             |
# | 10.1  | Release      | X   |      | X          | X           | X         | X         | X       | X             | X             | X                 |           | X    |                |                   |                      |                       |                       |                        |             |
# | -------------------- | --- | ---- | ---------- | ----------- | --------- | --------- | ------- | ------------- | ------------- | ----------------- | --------- | ---- | -------------- | ----------------- | -------------------- | --------------------- | --------------------- | ---------------------- | ----------- |
# | 10.2.1| Debug        | X   |      |            | X           | X         | X         | X       |               |               |                   |           | X    |                |                   |                      |                       |                       |                        |             |
# | 10.2.1| Release      | X   | X    | X          | X           | X         | X         | X       | X             | X             | X                 | X         | X    | X              | X                 |                      |                       | X                     |                        | X           |
# +------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

exclude:
  ################
  # docs
  ################
  # Just run on 10.2 Release
  - xcode_version: 9.2
    target: docs
  - xcode_version: 9.3
    target: docs
  - xcode_version: 9.4
    target: docs
  - xcode_version: 10.0
    target: docs
  - xcode_version: 10.1
    target: docs
  - target: docs
    configuration: Debug

  ################
  # ios-static
  ################
  # Skip Debug on everything but 9.2
  - xcode_version: 9.3
    target: ios-static
    configuration: Debug
  - xcode_version: 9.4
    target: ios-static
    configuration: Debug
  - xcode_version: 10.0
    target: ios-static
    configuration: Debug
  - xcode_version: 10.1
    target: ios-static
    configuration: Debug
  - xcode_version: 10.2.1
    target: ios-static
    configuration: Debug

  ################
  # ios-dynamic
  ################
  # Skip Debug on everything but 10.2
  - xcode_version: 9.2
    target: ios-dynamic
    configuration: Debug
  - xcode_version: 9.3
    target: ios-dynamic
    configuration: Debug
  - xcode_version: 9.4
    target: ios-dynamic
    configuration: Debug
  - xcode_version: 10.0
    target: ios-dynamic
    configuration: Debug
  - xcode_version: 10.1
    target: ios-dynamic
    configuration: Debug

  ################
  # ios-swift
  ################
  # Skip Debug on everything but 10.2
  - xcode_version: 9.2
    target: ios-swift
    configuration: Debug
  - xcode_version: 9.3
    target: ios-swift
    configuration: Debug
  - xcode_version: 9.4
    target: ios-swift
    configuration: Debug
  - xcode_version: 10.0
    target: ios-swift
    configuration: Debug
  - xcode_version: 10.1
    target: ios-swift
    configuration: Debug

  ################
  # osx-swift
  ################
  # Skip Debug on everything but 10.2
  - xcode_version: 9.2
    target: osx-swift
    configuration: Debug
  - xcode_version: 9.3
    target: osx-swift
    configuration: Debug
  - xcode_version: 9.4
    target: osx-swift
    configuration: Debug
  - xcode_version: 10.0
    target: osx-swift
    configuration: Debug
  - xcode_version: 10.1
    target: osx-swift
    configuration: Debug

  ################
  # watchos
  ################
  # Skip Debug on everything but 10.2
  - xcode_version: 9.2
    target: watchos
    configuration: Debug
  - xcode_version: 9.3
    target: watchos
    configuration: Debug
  - xcode_version: 9.4
    target: watchos
    configuration: Debug
  - xcode_version: 10.0
    target: watchos
    configuration: Debug
  - xcode_version: 10.1
    target: watchos
    configuration: Debug

  ################
  # cocoapods
  ################
  # Skip Debug
  - target: cocoapods-ios
    configuration: Debug
  - target: cocoapods-osx
    configuration: Debug
  - target: cocoapods-watchos
    configuration: Debug

  ################
  # swiftlint
  ################
  # Just run on 10.2 Release
  - xcode_version: 9.2
    target: swiftlint
  - xcode_version: 9.3
    target: swiftlint
  - xcode_version: 9.4
    target: swiftlint
  - xcode_version: 10.0
    target: swiftlint
  - xcode_version: 10.1
    target: swiftlint
  - target: swiftlint
    configuration: Debug

  ################
  # tvos
  ################
  # Skip Debug on everything but 10.2
  - xcode_version: 9.2
    target: tvos
    configuration: Debug
  - xcode_version: 9.3
    target: tvos
    configuration: Debug
  - xcode_version: 9.4
    target: tvos
    configuration: Debug
  - xcode_version: 10.0
    target: tvos
    configuration: Debug
  - xcode_version: 10.1
    target: tvos
    configuration: Debug

  ################
  # osx-encryption
  ################
  # Just run on 9.2/10.2 Release
  - xcode_version: 9.3
    target: osx-encryption
  - xcode_version: 9.4
    target: osx-encryption
  - xcode_version: 10.0
    target: osx-encryption
  - xcode_version: 10.1
    target: osx-encryption
  - target: osx-encryption
    configuration: Debug

  ################
  # osx-object-server
  ################
  # Just run on 9.2/10.2 Release
  - xcode_version: 9.3
    target: osx-object-server
  - xcode_version: 9.4
    target: osx-object-server
  - xcode_version: 10.0
    target: osx-object-server
  - xcode_version: 10.1
    target: osx-object-server
  - target: osx-object-server
    configuration: Debug

  ################
  # ios-device-objc-ios8
  ################
  # Just run on 9.2/10.2 Release
  - xcode_version: 9.3
    target: ios-device-objc-ios8
  - xcode_version: 10.0
    target: ios-device-objc-ios8
  - xcode_version: 10.1
    target: ios-device-objc-ios8
  - target: ios-device-objc-ios8
    configuration: Debug

  ################
  # ios-device-swift-ios8
  ################
  # Just run on 9.2/10.2 Release
  - xcode_version: 9.3
    target: ios-device-swift-ios8
  - xcode_version: 9.4
    target: ios-device-swift-ios8
  - xcode_version: 10.0
    target: ios-device-swift-ios8
  - xcode_version: 10.1
    target: ios-device-swift-ios8
  - target: ios-device-swift-ios8
    configuration: Debug

  ################
  # ios-device-objc-ios10
  ################
  # Just run on 9.2/10.2 Release
  - xcode_version: 9.3
    target: ios-device-objc-ios10
  - xcode_version: 9.4
    target: ios-device-objc-ios10
  - xcode_version: 10.0
    target: ios-device-objc-ios10
  - xcode_version: 10.1
    target: ios-device-objc-ios10
  - target: ios-device-objc-ios10
    configuration: Debug

  ################
  # ios-device-swift-ios10
  ################
  # Just run on 9.2/10.2 Release
  - xcode_version: 9.3
    target: ios-device-swift-ios10
  - xcode_version: 9.4
    target: ios-device-swift-ios10
  - xcode_version: 10.0
    target: ios-device-swift-ios10
  - xcode_version: 10.1
    target: ios-device-swift-ios10
  - target: ios-device-swift-ios10
    configuration: Debug

  ################
  # tvos-device
  ################
  # Just run on 10.2 Release
  - xcode_version: 9.2
    target: tvos-device
  - xcode_version: 9.3
    target: tvos-device
  - xcode_version: 9.4
    target: tvos-device
  - xcode_version: 10.0
    target: tvos-device
  - xcode_version: 10.1
    target: tvos-device
  - target: tvos-device
    configuration: Debug
