
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version:
 - 14.1
 - 14.2
 - 14.3.1
target:
 - swiftpm
 - swiftpm-debug
 - swiftpm-address
 - swiftpm-thread
 - swiftpm-ios
configuration:
 - N/A

exclude:

  - xcode_version: 14.2
    target: swiftpm

  - xcode_version: 14.1
    target: swiftpm-address

  - xcode_version: 14.2
    target: swiftpm-address

  - xcode_version: 14.1
    target: swiftpm-thread

  - xcode_version: 14.2
    target: swiftpm-thread
