
# Yaml Axis Plugin
# https://wiki.jenkins-ci.org/display/JENKINS/Yaml+Axis+Plugin
# This is a generated file produced by scripts/pr-ci-matrix.rb.

xcode_version:
 - 15.0
target:
 - docs
 - swiftlint
 - osx-swift
configuration:
 - N/A

exclude:
