included:
  - Realm/ObjectServerTests
  - RealmSwift
  - Realm/Swift
  - examples/installation/watchos/swift
  - examples/installation/osx/swift
  - examples/installation/ios/swift
  - examples/ios/swift
  - examples/tvos/swift
identifier_name:
  min_length: # not possible to disable this partial rule, so set it to zero
    warning: 0
    error: 0
  excluded:
    - _constructForTesting()
    - _constructPredicate()
    - _id
    - _name(for:)
    - _nilValue()
    - _nsError
    - _nsErrorDomain
    - _observe(_:)
    - _observe(_:_:)
    - _observe(_:_:_:)
    - _observe(_:on:_:)
    - _publisher
    - _realmColumnNames()
    - _realmObjectName()
    - _rlmCollection
    - _rlmCollection()
    - _rlmDefaultValue()
    - _rlmFromObjc(_:)
    - _rlmFromObjc(_:insideOptional:)
    - _rlmGetProperty(_:_:)
    - _rlmGetPropertyOptional(_:_:)
    - _rlmKeyPathRecorder(with:)
    - _rlmObjcValue
    - _rlmOptional
    - _rlmPopulateProperty(_:)
    - _rlmRequireObjc
    - _rlmRequiresCaching
    - _rlmSetAccessor(_:)
    - _rlmSetProperty(_:_:_:)
    - _rlmType
    - id
    - pk
    - to
disabled_rules:
  - block_based_kvo
  # SwiftLint considers 'Realm' and 'Realm.Private' to be duplicate imports
  # because we're using submodules in an unsual way, and normally the parent
  # module re-exports all of its children.
  - duplicate_imports
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - line_length
  - nesting
  - syntactic_sugar
  - todo
  - trailing_comma
  - type_body_length
  - vertical_whitespace
  # swiftlint complains about superfluous disable commands when the violation
  # occurs in an inactive #if and doesn't support conditionally disabling it
  - cyclomatic_complexity
  # #unavailable was implemented in Swift 5.6 so we can't use it until that's
  # the minimum version we support
  - unavailable_condition
