# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CocoaPodsExample' do
  use_frameworks!
  pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: 'swift-1.2'
  pod 'RealmSwift', :git => 'git@github.com:realm/realm-cocoa.git', branch: 'swift-1.2'
end

target 'CocoaPodsExampleTests' do
  use_frameworks!
  pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: 'swift-1.2'
  pod 'RealmSwift', :git => 'git@github.com:realm/realm-cocoa.git', branch: 'swift-1.2'
end
