name: Feature Request
description: Request a new feature or enhancement
labels: [Enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest improvements to the .NET SDK!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Tell us, what you would like to improve?
      placeholder: Describe your improvement...
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: How important is this improvement for you?
      options:
        - Dealbreaker
        - Would be a major improvement
        - I'd like to see it, but have a workaround
        - Fairly niche, but nice to have anyway