# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CocoaPodsExample' do
  pod 'Realm', :git => 'git@github.com:realm/realm-cocoa.git'
end

target 'CocoaPodsExampleTests' do
  pod 'Realm/Headers', :git => 'git@github.com:realm/realm-cocoa.git'
end
