use_frameworks!
branch = ENV['sha']

target 'CocoaPodsExample WatchKit Extension' do
  platform :watchos, '2.0'
  pod 'Realm', git: 'git@github.com:realm/realm-cocoa.git', branch: branch, submodules: true
  pod 'RealmSwift', git: 'git@github.com:realm/realm-cocoa.git', branch: branch, submodules: true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
