TEST_PROGRAMS = tutorial

tutorial_SOURCES = \
tutorial.m 

tutorial_CFLAGS  = -Wno-comment -fobjc-arc -fobjc-abi-version=2
tutorial_LDFLAGS = -fobjc-link-runtime
tutorial_LIBS    = ../src/tightdb/objc/libtightdb-objc.a

include ../src/generic.mk
