use_frameworks!
branch = ENV['sha']

target 'CocoaPodsExample WatchKit Extension' do
  platform :watchos, '2.0'
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: branch
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
    end
  end
end
