# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'CocoaPodsDynamicExample' do
  pod 'Realm', :git => 'git@github.com:realm/realm-cocoa.git'
end

target 'CocoaPodsDynamicExampleTests' do
  pod 'Realm', :git => 'git@github.com:realm/realm-cocoa.git'
end
