/*************************************************************************
 *
 * CAUTION:  DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE LOST!
 *
 * This file is generated by config.sh
 *
 *************************************************************************/

#define TIGHTDB_VERSION "unknown"

#define TIGHTDB_INSTALL_PREFIX      "/Users/tightdb/workspace/core_osx/install"
#define TIGHTDB_INSTALL_EXEC_PREFIX "/Users/tightdb/workspace/core_osx/install"
#define TIGHTDB_INSTALL_INCLUDEDIR  "/Users/tightdb/workspace/core_osx/install/include"
#define TIGHTDB_INSTALL_BINDIR      "/Users/tightdb/workspace/core_osx/install/bin"
#define TIGHTDB_INSTALL_LIBDIR      "/Users/tightdb/workspace/core_osx/install/lib"
#define TIGHTDB_INSTALL_LIBEXECDIR  "/Users/tightdb/workspace/core_osx/install/libexec"

#ifdef TIGHTDB_DEBUG
#  define TIGHTDB_MAX_BPNODE_SIZE 1000
#else
#  define TIGHTDB_MAX_BPNODE_SIZE 1000
#endif

#if 1
#  define TIGHTDB_ENABLE_REPLICATION 1
#endif

#if 0
#  define TIGHTDB_ENABLE_ALLOC_SET_ZERO 1
#endif
