TEST_PROGRAMS = test-installed

test_installed_SOURCES = test.mm
test_installed_CFLAGS  = -fobjc-arc -fobjc-abi-version=2
test_installed_LDFLAGS = -fobjc-link-runtime -ltightdb-objc -framework Cocoa

include generic.mk
