# Uncomment this line to define a global platform for your project
platform :ios, '14.0'
use_modular_headers!

branch = ENV['sha']

target 'CocoaPodsSubdependency' do
  pod 'Realm', git: 'https://github.com/realm/realm-swift.git', branch: branch
  pod 'RealmSwift', git: 'https://github.com/realm/realm-swift.git', branch: branch
  pod 'SubRealm', :path => '../CocoaPodsSubdependency'
end

target 'CocoaPodsSubdependencyTests' do
  pod 'Realm', git: 'https://github.com/realm/realm-swift.git', branch: branch
  pod 'RealmSwift', git: 'https://github.com/realm/realm-swift.git', branch: branch
  pod 'SubRealm', :path => '../CocoaPodsSubdependency'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
    end
  end
end
