# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

branch = ENV['sha']

target 'CocoaPodsExample' do
  use_frameworks!
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: branch
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: branch
end

target 'CocoaPodsExampleTests' do
  use_frameworks!
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: branch
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: branch
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
    end
  end
end
