# NOTE: This is a common file that is overwritten by realm/ci-actions sync service
# and should only be modified in that repository.

name: 'Auto Assign'
on:
  pull_request:
    types: [opened]

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@248761c4feb3917c1b0444e33fad1a50093b9847
