# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

branch = ENV['sha']

target 'CocoaPodsExample' do
  pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: branch, submodules: true
end

target 'CocoaPodsExampleTests' do
  pod 'Realm/Headers', git: 'https://github.com/realm/realm-cocoa.git', branch: branch, submodules: true
end
